#Adam Lamers
#Project Euler Problem 2
#STATUS:SOLVED

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#Find the sum of all the even-valued terms in the sequence which do not exceed four million.

f = [1, 2]
#print f[0]
#print f[1]
total = 0
answer = 0
while total < 4000000:
    
    f.append(f[len(f)-1] + f[len(f)-2])
    total = f[len(f)-1]
    
for i in range(1, len(f)):
    x = f[i] + f[i-1]
    if(x % 2 == 0):
        print x
        answer += x

print answer + f[1]
    
    
    
    